### ISSUE TITLE
Problems with AmmoCount

### ISSUE THREAD

**Issue by Bara20** [bcserv/smlib#31]
Since the last update.

A possible solution: https://forums.alliedmods.net/showpost.php?p=2291892&postcount=6

**Comment by berni2288** [comment]
Hi Bara20,
can you explain the difference between m_iPrimaryReserveAmmoCount  and m_iPrimaryAmmoCount ?

**Comment by Bara20** [comment]
I think m_iPrimaryAmmoCount and m_iSecondaryAmmoCount was replaced with m_iPrimaryReserveAmmoCount and m_iSecondaryReserveAmmoCount since this update http://blog.counter-strike.net/index.php/2015/04/11936/.

m_iPrimaryAmmoCount and m_iSecondaryAmmoCount doesn't exists anymore (netprop dump csgo).

**Comment by berni2288** [comment]
Answered in #32, closing this.

**Comment by Bara20** [comment]
https://github.com/bcserv/smlib/pull/32#issuecomment-98347754
Like this? https://forums.alliedmods.net/showthread.php?t=262841
