### ISSUE TITLE
Bugs in String_StartsWith and _EndsWith

### ISSUE THREAD

**Issue by F2** [bcserv/smlib#34]
The functions String_StartsWith and String_EndsWith have a behaviour inconsistent with other languages.

In C#, `"a".StartsWith("ab")` returns false.
In JavaScript, `'a'.startsWith('ab')` returns false.
But in SMLIB, `String_StartsWith("a", "ab")` returns true.

It is the same problem with String_EndsWith.
`String_EndsWith("a", "ba")` returns true when it should return false.

**Comment by peace-maker** [comment]
Thanks, fixed.

**Comment by berni2288** [comment]
Must be a bug in C# and Javascript then :)
