### ISSUE TITLE
Any plan on fixing it for the latest sourcemod?

### ISSUE THREAD

**Issue by WaterRatj** [bcserv/smlib#35]
Now you can't compile anymore since it gives errors.

* smlib/entities.inc(33) : error 138: const was specified twice.
* smlib/crypt.inc(426) : error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier
* smlib/effects.inc(158) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future.

Latest Sourcemod (1.7.2) & Latest Metamod(1.10.5)

**Comment by peace-maker** [comment]
Those were fixed last year. I'd recommend checking out the latest version from this git repository.
