### ISSUE TITLE
Bugs on compiling bot2player

### ISSUE THREAD

**Issue by Nerus87** [bcserv/smlib#43]
On compiling plugin "**bot2player**" I've got some errors:

- smlib/entities.inc(33) : error 138: const was specified twice
- smlib/crypt.inc(426) : error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier

[Plugin link.](https://forums.alliedmods.net/showthread.php?p=1950871)

Regards,
Nerus.

**Comment by peace-maker** [comment]
Please use the latest version of smlib from this repository. That was fixed a long time ago, but there hasn't been a new release yet.

**Comment by Nerus87** [comment]
I've used last one **this** build.
Please try compile this plugin with current version of smlib to see results.

**Comment by peace-maker** [comment]
Compiles fine. Produces some warnings outside of smlib though, but should still run fine.
Did you use [this](https://github.com/bcserv/smlib/archive/master.zip) package and NOT the release package?

**Comment by Nerus87** [comment]
It's ok, fully compiled.

Regards.
