### ISSUE TITLE
smlib/pluginmanager not exist (removed)

### ISSUE THREAD

**Issue by Nerus87** [bcserv/smlib#44]
Hi, I have problem with compile on new version of smlib, plugin need to have "smlib/pluginmanager".

Regards,
Nerus.

**Comment by peace-maker** [comment]
You can find it in this branch of smlib. It never got merged.
https://github.com/bcserv/smlib/tree/feature-pluginmanager

**Comment by Nerus87** [comment]
Ok thx, I've fixed plugin, basically "pluginmanager" is not required.
