### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by kmsraidboss** [bcserv/smlib#50]
I seem to be having the following issue when attempting to compile this plugin

`
// G:\CSGO\a_Plugins\Compile\executes.sp(353) : error 017: undefined symbol "PQ_Clear"
// G:\CSGO\a_Plugins\Compile\executes.sp(354) : error 017: undefined symbol "PQ_Clear"
// G:\CSGO\a_Plugins\Compile\executes.sp(879) : warning 217: loose indentation
// G:\CSGO\a_Plugins\Compile\executes.sp(977) : error 017: undefined symbol "PQ_Clear"
// G:\CSGO\a_Plugins\Compile\executes.sp(986) : warning 213: tag mismatch
// G:\CSGO\a_Plugins\Compile\executes.sp(995) : warning 213: tag mismatch
`

This is happening when compiling on both the current stable SM release and the dev release. I've attempted to troubleshoot and have ensured all dependencies are in place in their correct paths. Any help on this would be appreciated.

**Comment by peace-maker** [comment]
I don't see how this is related to this library.

**Comment by kmsraidboss** [comment]
I am so sorry, I had this and executes git open at the same time, I must have just selected the wrong one. Again, very sorry for wasting your time.
