### ISSUE TITLE
SM 1.110

### ISSUE THREAD

**Issue by xMaZax** [bcserv/smlib#53]
E:\Other\CSGO\Compilator\sourcemod-1.10.0-git6381-linux\include\smlib/entities.inc(1773) : fatal error 196: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs

**Comment by vintorxca** [comment]
yeah I have this error too
can someone fix to the new syntax?

**Comment by peace-maker** [comment]
Check out the transitional_syntax branch. I guess it's time to drop support for pre 1.10 compilers on the master branch.

https://github.com/bcserv/smlib/tree/transitional_syntax
