### ISSUE TITLE
Add infinite loops to the Api

### ISSUE THREAD

**Issue by DJPlaya** [bcserv/smlib#57]
This Problem came up when i had to Code an Loop without an Condition to run, the Loop would then be ended with a "break".
After discussing this Problem (here > https://forums.alliedmods.net/showthread.php?p=2656813) we have found an simple Solution for it
`#define loop for(;;)`
This allows us to just do:
```
loop
{...}
```
This is something small, yet its nice to have i think

**Comment by peace-maker** [comment]
Inventing new keywords for a language makes it harder to read for others.

`for(;;)` looks perfectly fine to me.

**Comment by DJPlaya** [comment]
I had the same Thoughts when the new Syntax came out ^^
