### ISSUE TITLE
1.10 Compilation Warning on transitional_syntax branch

### ISSUE THREAD

**Issue by sneak-it** [bcserv/smlib#58]
When compiling with transitional syntax branch on 1.10-6463, this warning occurs:

`/include/smlib/colors.inc(78) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs`

**Comment by JoinedSenses** [comment]
For now, you'll have to use #include <smlib/whatever>. Old style enum structs are deprecated and new enum structs don't allow for bracket initialization. Fix is to either initialize the global ES via a function or wait for a resolution to https://github.com/alliedmodders/sourcepawn/issues/412

**Comment by sneak-it** [comment]
Even if you include a specific portion of smlib, each "module" includes the rest of the library, so the warning persists regardless in compilation.

See for example: https://github.com/bcserv/smlib/blob/transitional_syntax/scripting/include/smlib/clients.inc#L27-L37

**Comment by JoinedSenses** [comment]
https://github.com/bcserv/smlib/pull/59

**Comment by peace-maker** [comment]
Fixed in #59
