### ISSUE TITLE
NEw syntax 1.11 need update

### ISSUE THREAD

**Issue by maclarens** [bcserv/smlib#72]
Compiling sm_dev_cmds.sp...
SourcePawn Compiler 1.11.0.6934
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

./include/smlib/entities.inc(1773) : error 418: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs
./include/smlib/entities.inc(1773) : error 001: expected token: "-identifier-", but found "public"
./include/smlib/entities.inc(1773) : error 122: expected type expression

**Comment by peace-maker** [comment]
Check the [transitional_syntax](https://github.com/bcserv/smlib/tree/transitional_syntax) branch for 1.7+ syntax.
